export const fixture = {
  version: 1,
  site: {
    name: "Photographer",
    tagline: "Photography",
    location: "Montréal",
    intro: "Selected work.",
    description: "Photos",
    email: "photo@example.com",
    aboutTitle: "About",
    about: "Biography",
    aboutImage: "assets/about.jpg",
    gear: "Camera",
    socials: [{ label: "Social", url: "https://example.com/" }],
  },
  categories: [{ id: "aviation", label: "Aviation" }],
  photos: [
    {
      id: "photo-one",
      title: "A plane",
      alt: "A plane in flight",
      category: "aviation",
      image: "assets/one.jpg",
      thumbnail: "media/one-640.webp",
      display: "media/one-1280.webp",
      large: "media/one-1920.webp",
      width: 2000,
      height: 1000,
      published: true,
      featured: true,
    },
    {
      id: "photo-two",
      title: "Another plane",
      alt: "A plane on the ground",
      category: "aviation",
      image: "assets/two.jpg",
      width: 1200,
      height: 800,
      published: true,
      featured: false,
    },
  ],
};
