import { escapeHTML as e } from '../app/shared.js';
import { collections, defaultCollection, gearItems, siteSettings } from '../app/config.js';
import { studioIcon as icon } from './ui.js';

const heading = (title, detail) => `<div class="section-heading"><h2>${title}</h2><p class="hint">${detail}</p></div>`;

export function collectionEditorView(data) {
  const items = collections(data, { includeHidden: true });
  return `<section class="panel collection-defaults">${heading('首页与浏览方式', '决定访客第一次打开网站时看到什么。')}
    <div class="form-grid"><label>默认作品集合<select id="default-collection">${collections(data).map(item => `<option value="${e(item.id)}" ${item.id === defaultCollection(data) ? 'selected' : ''}>${e(item.label)}</option>`).join('')}</select></label>
    <label>默认浏览方式<select id="default-photo-view"><option value="multi" ${data.collections?.defaultView !== 'single' ? 'selected' : ''}>多图浏览</option><option value="single" ${data.collections?.defaultView === 'single' ? 'selected' : ''}>单图浏览</option></select></label></div>
    <p class="hint">分类直达链接仍进入对应分类。默认集合被隐藏或删除时，自动改为第一个可见集合。</p></section>
    ${heading('作品集合', '用箭头调整菜单顺序。隐藏题材分类时，该分类照片也会退出公开精选。')}
    <div class="category-list">${items.map((item, index) => `<section class="collection-row" data-collection="${e(item.id)}">
      <div class="collection-heading"><span class="badge">${item.id === 'all' ? '精选集合' : '题材分类'}</span><div class="collection-actions"><button data-collection-move="${e(item.id)}" data-direction="-1" aria-label="${e(item.label)}上移" ${index === 0 ? 'disabled' : ''}>${icon('up')}</button><button data-collection-move="${e(item.id)}" data-direction="1" aria-label="${e(item.label)}下移" ${index === items.length - 1 ? 'disabled' : ''}>${icon('down')}</button></div></div>
      <label>显示名称<input data-collection-label="${e(item.id)}" value="${e(item.label)}" maxlength="80" required></label>
      <label>集合简介<textarea data-collection-description="${e(item.id)}" rows="2" maxlength="400" placeholder="可选，用于介绍这个作品集合">${e(item.description || '')}</textarea></label>
      <div class="collection-footer"><label class="inline-check"><input type="checkbox" data-collection-visible="${e(item.id)}" ${item.visible !== false ? 'checked' : ''}>在网站显示</label><code>${e(item.id)}</code>${item.id !== 'all' ? `<button data-delete-category="${e(item.id)}">删除分类</button>` : ''}</div></section>`).join('')}</div>
    <details class="panel new-collection"><summary>添加作品分类</summary><p class="hint">固定 ID 用于分类链接，建议使用简短英文；显示名称可以自由填写。</p><form id="new-category" class="new-category"><label>固定 ID<input name="id" placeholder="例如 travel" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required maxlength="60"></label><label>显示名称<input name="label" placeholder="例如 Travel" required maxlength="80"></label><button class="primary" type="submit">添加分类</button></form></details>`;
}

export function siteEditorView(data, image) {
  const site = siteSettings(data.site);
  const sharingPhotos = data.photos.filter(p => p.published && data.categories.some(c => c.id === p.category && c.visible !== false));
  const field = (key, label, multiline = false) => `<label>${label}${multiline ? `<textarea name="${key}" rows="4">${e(site[key])}</textarea>` : `<input name="${key}" value="${e(site[key])}" ${key === 'email' ? 'type="email"' : ''}>`}</label>`;
  const sections = [['profile','个人资料'],['navigation','品牌与导航'],['about','简介页面'],['contact','联系与页脚'],['equipment','摄影器材'],['social','社交平台'],['sharing','搜索与分享']];
  return `<nav class="settings-nav" aria-label="网站内容分区">${sections.map(([id, label]) => `<a href="#settings-${id}">${label}</a>`).join('')}</nav><form class="settings-form" id="settings-form">
    <section class="settings-section" id="settings-profile">${heading('个人资料', '摄影师名称、城市和网站简介。')}<div class="form-grid">${field('name','摄影师名称')}${field('location','所在城市')}${field('email','联系邮箱')}${field('tagline','品牌无障碍描述')}</div>${field('description','网站简介',true)}</section>
    <section class="settings-section" id="settings-navigation">${heading('品牌与导航', '保留你的品牌外观，自由修改文字和页面入口。')}<div class="form-grid">${field('brandName','Logo 上行文字')}${field('brandTitle','Logo 主文字')}${field('workLabel','作品菜单名称')}${field('aboutLabel','简介菜单名称')}${field('contactLabel','联系菜单名称')}${field('contactLinkLabel','联系链接文字')}</div><div class="check-row">${['About','Contact'].map(page => `<label><input type="checkbox" name="show${page}" ${site[`show${page}`] ? 'checked' : ''}>在导航显示${page === 'About' ? '简介' : '联系'}</label>`).join('')}</div></section>
    <section class="settings-section" id="settings-about">${heading('简介页面', '介绍你自己，并为简介选择一张照片。')}${field('aboutTitle','简介标题')}${field('about','个人介绍（空行分段）',true)}
      <div class="about-image-editor"><img src="${e(image(site.aboutImage))}" alt="当前简介照片"><div><label>简介照片<select id="about-library"><option value="${e(site.aboutImage)}">保留当前照片</option>${data.photos.map(photo => `<option value="${e(photo.image)}">${e(photo.title)}${photo.published ? '' : '（未在画廊发布）'}</option>`).join('')}</select></label><input type="hidden" name="aboutImage" value="${e(site.aboutImage)}"><button type="button" class="secondary" id="upload-about">${icon('upload')}上传替换照片</button><input id="about-upload-input" type="file" accept="image/jpeg,image/png,image/webp" hidden><p class="hint">这张照片将在简介页公开显示。上传替换只更换简介照片，不向作品画廊添加照片。</p></div></div>${field('aboutImageAlt','照片无障碍描述')}</section>
    <section class="settings-section" id="settings-contact">${heading('联系与页脚', '访客联系你的入口，以及页面底部的说明。')}${field('contactText','联系页面说明')}${field('footerText','页脚版权说明')}</section>
    <section class="settings-section" id="settings-equipment">${heading('摄影器材', '每件器材单独管理，在简介页面按行展示。')}${field('gearLabel','器材区域标题')}<div class="equipment-list">${gearItems(site.gear).map((item,i) => `<div class="equipment-row"><label class="sr-only" for="gear-${i}">器材 ${i + 1}</label><input id="gear-${i}" name="gear-${i}" data-gear value="${e(item)}" maxlength="200" placeholder="相机、镜头或配件"><button type="button" data-remove-gear="${i}" aria-label="移除器材 ${i + 1}">${icon('close')}</button></div>`).join('')}</div><button type="button" class="secondary" id="add-gear">＋ 添加一件器材</button></section>
    <section class="settings-section" id="settings-social">${heading('社交平台', '前两个作为主要平台显示，用箭头调整顺序。')}<div class="social-list">${site.socials.map((social,i) => `<div class="social-row"><input name="social-label-${i}" value="${e(social.label)}" aria-label="社交平台 ${i + 1}" required><input name="social-url-${i}" type="url" value="${e(social.url)}" aria-label="社交链接 ${i + 1}" required><div class="social-actions"><button type="button" data-social-move="${i}" data-direction="-1" aria-label="链接上移" ${i === 0 ? 'disabled' : ''}>${icon('up')}</button><button type="button" data-social-move="${i}" data-direction="1" aria-label="链接下移" ${i === site.socials.length - 1 ? 'disabled' : ''}>${icon('down')}</button><button type="button" data-remove-social="${i}" aria-label="移除链接">${icon('close')}</button></div></div>`).join('')}</div><button type="button" class="secondary" id="add-social">＋ 添加社交链接</button></section>
    <section class="settings-section" id="settings-sharing">${heading('搜索与分享', '选择分享链接时显示的封面。')}<label>分享封面<select name="shareImage"><option value="">默认品牌封面</option>${data.site.shareImage && !sharingPhotos.some(p => p.image === data.site.shareImage) ? `<option value="${e(data.site.shareImage)}" selected>保留当前分享封面</option>` : ''}${sharingPhotos.map(p => `<option value="${e(p.image)}" ${data.site.shareImage === p.image ? 'selected' : ''}>${e(p.title)}</option>`).join('')}</select></label><p class="hint">保存时同步静态页面与分享信息；网站部署及分享平台缓存更新需要时间。分享封面公开显示。</p></section>
    <div class="settings-footer"><button type="submit" class="secondary">校验网站内容</button><p class="hint">修改会自动进入草稿。先打开作品预览，确认后点右上角“保存更改”发布。</p></div></form>`;
}
